name: Bug report
description: Create a bug report
labels: ["needs triage"]
type: Bug
body:
  - type: input
    attributes:
      label: Nutgram version
      description: "The version of Nutgram you are using."
    validations:
      required: true

  - type: input
    attributes:
      label: PHP version
      description: "PHP version you are running on."
      placeholder: "8.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Framework
      description: "PHP framework you are using, if applicable."
      placeholder: "Laravel 10.x"
      value: "No Framework"
    validations:
      required: false

  - type: input
    attributes:
      label: Cache driver
      description: "The cache driver you are using or configured in you framework (ex. Filesystem Cache, Laravel+Redis, etc), if none, by default Nutgram uses an internal non persistent array cache."
      placeholder: "ArrayCache"
    validations:
      required: true

  - type: input
    attributes:
      label: OS
      description: "The Operating System you are using."
    validations:
      required: true

  - type: input
    attributes:
      label: Dev environment
      description: "The environment you are using (ex. Valet, phpmon, Homestead, Herd, Laragon, Docker, etc)."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: "Describe the steps to reproduce the behavior."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."

  - type: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/nutgram/nutgram/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/nutgram/nutgram/blob/master/.github/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://nutgram.dev/docs/introduction).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/nutgram/nutgram/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/nutgram/nutgram/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
