name: Bug report
description: Create a bug report
title: "[BUG] "
labels: ["Bug"]
body:
    - type: input
      attributes:
          label: Nutgram version
          description: "The version of Nutgram you are using."
      validations:
          required: true
    
    - type: input
      attributes:
          label: PHP version
          description: "PHP version you are running on."
          placeholder: "8.0"
      validations:
          required: true
    
    - type: input
      attributes:
          label: Framework
          description: "PHP framework you are using, if applicable."
          placeholder: "Laravel 10.x"
          value: "No Framework"
      validations:
          required: false
        
    - type: input
      attributes:
          label: Cache driver
          description: "The cache driver you are using or configured in you framework (ex. Filesystem Cache, Laravel+Redis, etc), if none, by default Nutgram uses an internal non persistent array cache."
          placeholder: "ArrayCache"
      validations:
          required: true

    - type: textarea
      attributes:
          label: Describe the bug
          description: "A clear and concise description of what the bug is."
      validations:
          required: true

    - type: textarea
      attributes:
          label: To Reproduce
          description: "Describe the steps to reproduce the behavior."
          value: |
                  1. Go to '...'
                  2. Click on '....'
                  3. Scroll down to '....'
                  4. See error
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected behavior
          description: "A clear and concise description of what you expected to happen."
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots
          description: "If applicable, add screenshots to help explain your problem."

    - type: textarea
      attributes:
          label: Additional context
          description: "Add any other context about the problem here."
