name: Feature request
description: Suggest an idea for this project
labels: ["needs triage"]
type: Feature
body:
    - type: markdown
      attributes:
        value: |
          Thanks for your interest in the project and taking the time to fill out this feature report!

    - type: dropdown
      attributes:
        label: Package type
        description: Select the Nutgram package relevant to your feature request
        options:
          - nutgram/nutgram
          - nutgram/laravel
          - nutgram/symfony-bundle
        default: 0
        validations:
          required: true

    - type: textarea
      attributes:
          label: Description
          description: "Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!"

    - type: textarea
      attributes:
          label: Suggested solution
          description: "In class [xy] we could implement [xyz] to achieve [abc]."

    - type: textarea
      attributes:
          label: Alternative
          description: "Clear and concise description of any alternative solutions or features you've considered."

    - type: textarea
      attributes:
          label: Additional context
          description: "Any other context or screenshots about the feature request here."

    - type: checkboxes
      attributes:
        label: Validations
        description: Before submitting the issue, please make sure you do the following
        options:
          - label: Follow our [Code of Conduct](https://github.com/nutgram/nutgram/blob/master/CODE_OF_CONDUCT.md)
            required: true
          - label: Read the [Contributing Guidelines](https://github.com/nutgram/nutgram/blob/master/.github/CONTRIBUTING.md).
            required: true
          - label: Read the [docs](https://nutgram.dev/docs/introduction).
            required: true
          - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
            required: true
